exports.projectsData = [
  {
    id: 125,
    type: "video",
    title: "Flashcard Quiz With React",
    category: ["web-dev"],
    tech: ["React", "API", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Apr 11, 2020",
    projectURL: "https://www.youtube.com/watch?v=hEtZ040fsD8",
  },
  {
    id: 124,
    type: "video",
    title: "Whack-a-Mole with pure JavaScript",
    category: ["web-dev", "game-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Feb 5, 2020",
    projectURL: "https://www.youtube.com/watch?v=o93jem7oPnA",
  },
  {
    id: 123,
    type: "video",
    title: "NOKIA 3310 Snake Game using JavaScript",
    category: ["web-dev", "game-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Jan 26, 2020",
    projectURL: "https://www.youtube.com/watch?v=rui2tRRVtc0",
  },
  {
    id: 122,
    type: "video",
    title: "Rock Paper Scissors in vanilla JavaScript",
    category: ["web-dev", "game-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Nov 15, 2019",
    projectURL: "https://www.youtube.com/watch?v=mXrTIpYoCPE",
  },
  {
    id: 121,
    type: "video",
    title: "Tetris with pure JavaScript",
    category: ["web-dev", "game-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Nov 15, 2019",
    projectURL: "https://www.youtube.com/watch?v=GWPGz9hrVMk",
  },
  {
    id: 120,
    type: "article",
    title: "Twitter Sentiment Analysis using CNN",
    category: ["ml-ai"],
    tech: ["Python", "Matplotlib", "Numpy", "Pandas"],
    datePublished: "Dec 8, 2017",
    projectURL: "https://towardsdatascience.com/another-twitter-sentiment-analysis-bb5b01ebad90",
  },
  {
    id: 119,
    type: "article",
    title: "Meme Maker with React",
    category: ["web-dev"],
    tech: ["React", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Dec 24, 2018",
    projectURL:
      "https://medium.com/free-code-camp/react-for-beginners-building-a-meme-maker-with-react-7164d3d3e55f",
  },
  {
    id: 118,
    type: "video",
    title: "Evernote Clone with React",
    category: ["web-dev"],
    tech: ["React", "Firebase", "Node", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Jul 15, 2019",
    projectURL: "https://www.youtube.com/watch?v=I250xdtUvy8",
  },
  {
    id: 117,
    type: "video",
    title: "Developer Meetup App with Vue",
    category: ["web-dev"],
    tech: ["Vue", "Firebase", "Vuetify", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Mar 4, 2020",
    projectURL:
      "https://www.youtube.com/watch?v=FXY1UyQfSFw&list=PL55RiY5tL51qxUbODJG9cgrsVd7ZHbPrt&index=2&t=32s",
  },
  {
    id: 116,
    type: "article",
    title: "Real-Time Chat App with Vue",
    category: ["web-dev"],
    tech: ["Vue", "Firebase", "Vuex", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Oct 16, 2017",
    projectURL: "https://vuejsdevelopers.com/2017/10/16/vue-js-firestore/",
  },
  {
    id: 115,
    type: "article",
    title: "Cryptocurrency Tracker with Vue",
    category: ["web-dev"],
    tech: ["Vue", "Vuetify", "API", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Feb 15, 2018",
    projectURL:
      "https://medium.com/eliteng/build-a-cryptocurrency-tracker-with-vue-js-c0efd4c0139e",
  },
  {
    id: 114,
    type: "article",
    title: "Multiplayer Quiz Game with Vue",
    category: ["game-dev", "web-dev"],
    tech: ["Vue", "Pusher", "Node", "Express", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Apr 8, 2018",
    projectURL:
      "https://medium.com/front-end-weekly/build-a-multiplayer-quiz-game-with-vue-js-ca22bad8fb52",
  },
  {
    id: 113,
    type: "article",
    title: "Minesweeper Game with Vue",
    category: ["game-dev", "web-dev"],
    tech: ["Vue", "Vuex", "Vuetify", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Sep 2, 2019",
    projectURL:
      "https://medium.com/javascript-in-plain-english/minesweeper-rebuild-with-vue-vuex-and-vuetify-ab1921e5258e",
  },
  {
    id: 112,
    type: "article",
    title: "Instagram Clone with Vue",
    category: ["web-dev"],
    tech: ["Vue", "CSSGram", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Dec 19, 2019",
    projectURL:
      "https://medium.com/fullstackio/tutorial-build-an-instagram-clone-with-vue-js-and-cssgram-24a9f3de0408",
  },
  {
    id: 111,
    type: "article",
    title: "Hacker News Clone with Angular",
    category: ["web-dev"],
    tech: ["Angular", "Lighthouse", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Oct 24, 2018",
    projectURL:
      "https://medium.com/crowdbotics/learn-to-build-a-simple-progressive-web-app-pwa-with-angular-and-lighthouse-hacker-news-clone-51aca763032f",
  },
  {
    id: 110,
    type: "article",
    title: "Chat Interface",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Dec 19, 2019",
    projectURL: "https://www.florin-pop.com/blog/2019/04/chat-interface/",
  },
  {
    id: 109,
    type: "article",
    title: "Pure CSS3 Tooltip",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Dec 18, 2019",
    projectURL: "https://www.florin-pop.com/blog/2019/05/pure-css-tooltip/",
  },
  {
    id: 108,
    type: "article",
    title: "Social Media Buttons",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Jul 11, 2019",
    projectURL: "https://www.florin-pop.com/blog/2019/07/social-media-buttons/",
  },
  {
    id: 107,
    type: "article",
    title: "Testimonial Card",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Jul 17, 2019",
    projectURL: "https://www.florin-pop.com/blog/2019/07/testimonial-card/",
  },
  {
    id: 106,
    type: "article",
    title: "Navigation Bar with CSS3 Flexbox",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Jul 9, 2019",
    projectURL: "https://freshman.tech/flexbox-navbar/",
  },
  {
    id: 105,
    type: "article",
    title: "Mobile App Layout with CSS3 Flexbox",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Oct 23, 2019",
    projectURL: "https://freshman.tech/flexbox-mobile-app/",
  },
  {
    id: 104,
    type: "article",
    title: "Reddit-inspired Loading Spinner",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    datePublished: "Feb 19, 2019",
    projectURL:
      "https://www.freecodecamp.org/news/how-to-build-a-reddit-inspired-loading-spinner-with-only-html-and-css-5b2fca3fdca/",
  },
  {
    id: 103,
    type: "article",
    title: "Calendar with CSS3 Grid",
    category: ["web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Jul 16, 2019",
    projectURL: "https://www.freecodecamp.org/news/how-to-build-a-calendar-with-css-grid/",
  },
  {
    id: 102,
    type: "video",
    title: "Tetris Game in React",
    category: ["game-dev", "web-dev"],
    tech: ["React", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Aug 14, 2019",
    projectURL: "https://www.youtube.com/watch?v=ZGOaCxX8HIU",
  },
  {
    id: 101,
    type: "article",
    title: "2D Breakout Game",
    category: ["game-dev", "web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Oct 26, 2016",
    projectURL:
      "https://developer.mozilla.org/en-US/docs/Games/Tutorials/2D_Breakout_game_pure_JavaScript",
  },
  {
    id: 100,
    type: "article",
    title: "Sprite Animation",
    category: ["game-dev", "web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Jan 13, 2018",
    projectURL:
      "https://medium.com/dailyjs/how-to-build-a-simple-sprite-animation-in-javascript-b764644244aa",
  },
  {
    id: 99,
    type: "article",
    title: "Snake Game",
    category: ["game-dev", "web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Jul 5, 2018",
    projectURL:
      "https://www.freecodecamp.org/news/think-like-a-programmer-how-to-build-snake-using-only-javascript-html-and-css-7b1479c3339e/",
  },
  {
    id: 98,
    type: "article",
    title: "Memory Game",
    category: ["game-dev", "web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Aug 28, 2018",
    projectURL:
      "https://medium.com/free-code-camp/vanilla-javascript-tutorial-build-a-memory-game-in-30-minutes-e542c4447eae",
  },
  {
    id: 97,
    type: "article",
    title: "Simple Authentication and Authorization",
    category: ["web-dev"],
    tech: ["GraphQL", "Apollo", "Node", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Mar 27, 2020",
    projectURL:
      "https://medium.com/javascript-in-plain-english/simple-authentication-and-authorization-in-graphql-5293c0458fc",
  },
  {
    id: 96,
    type: "article",
    title: "Cryptocurrency Tracker",
    category: ["web-dev"],
    tech: ["NextJS", "GraphQL", "Apollo", "Node", "JavaScript", "HTML5", "CSS3"],
    datePublished: "Mar 24, 2020",
    projectURL:
      "https://medium.com/javascript-in-plain-english/build-a-cryptocurrency-tracker-with-next-js-and-apollo-graphql-c776cff6b8bf",
  },
  {
    id: 95,
    type: "article",
    title: "Instant Search With Vanilla Javascript",
    category: ["web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Jun 21, 2019",
    projectURL: "https://www.florin-pop.com/blog/2019/06/vanilla-javascript-instant-search/",
  },
  {
    id: 94,
    type: "article",
    title: "Calculator App",
    category: ["web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "Mar 21, 2018",
    projectURL: "https://zellwk.com/blog/calculator-part-1",
  },
  {
    id: 93,
    type: "video",
    title: "Tanks Shooter",
    category: ["game-dev"],
    tech: ["3D", "Unity", "C#"],
    datePublished: "Jul 24, 2019",
    projectURL: "https://learn.unity.com/project/tanks-tutorial",
  },
  {
    id: 92,
    type: "video",
    title: "2D Roguelike",
    category: ["game-dev"],
    tech: ["2D", "Unity", "C#"],
    datePublished: "May 22, 2019",
    projectURL: "https://learn.unity.com/project/2d-roguelike-tutorial",
  },
  {
    id: 91,
    type: "video",
    title: "John Lemon's Haunted Jaunt 3D",
    category: ["game-dev"],
    tech: ["3D", "Unity", "C#"],
    datePublished: "Apr 12, 2019",
    projectURL: "https://learn.unity.com/project/john-lemon-s-haunted-jaunt-3d-beginner",
  },
  {
    id: 90,
    type: "video",
    title: "VR Beginner: The Escape Room",
    category: ["game-dev"],
    tech: ["VR", "Unity", "C#"],
    datePublished: "Feb 24, 2020",
    projectURL: "https://learn.unity.com/project/vr-beginner-the-escape-room",
  },
  {
    id: 89,
    type: "video",
    title: "Ruby's Adventure",
    category: ["game-dev"],
    tech: ["2D", "Unity", "C#"],
    datePublished: "March 2, 2019",
    projectURL: "https://learn.unity.com/project/ruby-s-2d-rpg",
  },
  {
    id: 88,
    type: "video",
    title: "RPG Game",
    category: ["game-dev"],
    tech: ["2D", "Unity", "C#"],
    datePublished: "Jun 11, 2019",
    projectURL: "https://learn.unity.com/project/creator-kit-rpg",
  },
  {
    id: 87,
    type: "video",
    title: "Roll-a-ball",
    category: ["game-dev"],
    tech: ["3D", "Unity", "C#"],
    datePublished: "Mar 2, 2019",
    projectURL: "https://learn.unity.com/project/roll-a-ball-tutorial",
  },
  {
    id: 86,
    type: "video",
    title: "FPS Microgame",
    category: ["game-dev"],
    tech: ["Unity", "C#"],
    datePublished: "Oct 24, 2019",
    projectURL: "https://learn.unity.com/project/fps-template?courseId=5c59cf22edbc2a001f59aa5d",
  },
  {
    id: 85,
    type: "video",
    title: "Platformer Microgame",
    category: ["game-dev"],
    tech: ["Unity", "C#", "2D"],
    datePublished: "Apr 12, 2019",
    projectURL:
      "https://learn.unity.com/project/2d-platformer-template?courseId=5c59cf22edbc2a001f59aa5d",
  },
  {
    id: 84,
    type: "video",
    title: "Karting Microgame",
    category: ["game-dev"],
    tech: ["Unity", "C#"],
    datePublished: "Mar 20, 2019",
    projectURL:
      "https://learn.unity.com/project/karting-template?courseId=5c59cf22edbc2a001f59aa5d",
  },
  {
    id: 83,
    type: "video",
    title: "TrueCaller Clone",
    category: ["mob-dev"],
    tech: ["Java", "MySQL", "XAMPP", "Android"],
    datePublished: "Jun 15, 2015",
    projectURL: "https://www.youtube.com/watch?v=mlEdGe4vui4",
  },
  {
    id: 82,
    type: "video",
    title: "Weather App",
    category: ["mob-dev"],
    tech: ["Java", "API", "Android"],
    datePublished: "Oct 4, 2016",
    projectURL: "https://www.youtube.com/watch?v=wAV2Uqv9KLo",
  },
  {
    id: 81,
    type: "video",
    title: "E-Commerce App",
    category: ["mob-dev"],
    tech: ["Java", "Firebase", "Android"],
    datePublished: "Oct 11, 2018",
    projectURL:
      "https://www.youtube.com/watch?v=6keVIot98QU&list=PLxefhmF0pcPlqmH_VfWneUjfuqhreUz-O&index=1",
  },
  {
    id: 80,
    type: "video",
    title: "Chat App",
    category: ["mob-dev"],
    tech: ["Java", "Firebase", "Android"],
    datePublished: "Aug 18, 2018",
    projectURL:
      "https://www.youtube.com/watch?v=fJWFeW09qeE&list=PLzLFqCABnRQftQQETzoVMuteXzNiXmnj8&index=1",
  },
  {
    id: 79,
    type: "article",
    title: "Todo App",
    category: ["mob-dev"],
    tech: ["Flutter", "Dart", "Android", "iOS"],
    datePublished: "Jun 7, 2018",
    projectURL: "https://medium.com/the-web-tub/making-a-todo-app-with-flutter-5c63dab88190",
  },
  {
    id: 78,
    type: "video",
    title: "Travel App UI",
    category: ["mob-dev"],
    tech: ["Flutter", "Dart", "Android", "iOS"],
    datePublished: "Oct 23, 2019",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=CSa6Ocyog4U",
  },
  {
    id: 77,
    type: "article",
    title: "Taylor Swift Lyrics Generator",
    category: ["ml-ai"],
    tech: ["Python", "Keras", "Numpy", "Pandas"],
    datePublished: "Apr 19, 2018",
    projectURL:
      "https://towardsdatascience.com/ai-generates-taylor-swifts-song-lyrics-6fd92a03ef7e",
  },
  {
    id: 76,
    type: "article",
    title: "MNIST Digit Recognizer",
    category: ["ml-ai"],
    tech: ["Python", "Keras", "TensorFlow", "Numpy", "SciKit", "Pandas", "Matplotlib"],
    datePublished: "Apr 19, 2018",
    projectURL:
      "https://medium.com/@lvarruda/how-to-get-top-2-position-on-kaggles-mnist-digit-recognizer-48185d80a2d4",
  },
  {
    id: 75,
    type: "article",
    title: "Train a Model to Generate Colors",
    category: ["ml-ai"],
    tech: ["Python", "Keras", "TensorFlow", "Numpy"],
    datePublished: "May 3, 2018",
    projectURL:
      "https://heartbeat.fritz.ai/how-to-train-a-keras-model-to-generate-colors-3bc79e54971b",
  },

  {
    id: 74,
    type: "article",
    title: "Image Caption Generator",
    category: ["ml-ai"],
    tech: ["Python", "TensorFlow", "Numpy"],
    datePublished: "11 APRIL 2018",
    projectURL:
      "https://medium.freecodecamp.org/building-an-image-caption-generator-with-deep-learning-in-tensorflow-a142722e9b1f",
  },
  {
    id: 73,
    type: "article",
    title: "Break a Captcha System using CNN",
    category: ["ml-ai"],
    tech: ["Python", "Keras", "TensorFlow", "OpenCV", "Numpy"],
    datePublished: "Dec 13, 2017",
    projectURL:
      "https://medium.com/@ageitgey/how-to-break-a-captcha-system-in-15-minutes-with-machine-learning-dbebb035a710",
  },
  {
    id: 72,
    type: "article",
    title: "Generate an Average Face",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy", "C/C++"],
    datePublished: "MAY 7, 2016",
    projectURL: "https://www.learnopencv.com/average-face-opencv-c-python-tutorial/",
  },
  {
    id: 71,
    type: "article",
    title: "Image Stitching",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "December 17, 2018",
    projectURL: "https://www.pyimagesearch.com/2018/12/17/image-stitching-with-opencv-and-python/",
  },
  {
    id: 70,
    type: "article",
    title: "Hand Keypoint Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy", "C/C++"],
    datePublished: "OCTOBER 8, 2018",
    projectURL:
      "https://www.learnopencv.com/hand-keypoint-detection-using-deep-learning-and-opencv/",
  },
  {
    id: 69,
    type: "article",
    title: "Eigenface",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy", "C/C++"],
    datePublished: "JANUARY 18, 2018",
    projectURL: "https://www.learnopencv.com/eigenface-using-opencv-c-python/",
  },
  {
    id: 68,
    type: "article",
    title: "Drone Target Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "May 4, 2015",
    projectURL:
      "https://www.pyimagesearch.com/2015/05/04/target-acquired-finding-targets-in-drone-and-quadcopter-video-streams-using-python-and-opencv/",
  },
  {
    id: 67,
    type: "article",
    title: "Object Detection using Mask R-CNN",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "OCTOBER 1, 2018",
    projectURL:
      "https://www.learnopencv.com/deep-learning-based-object-detection-and-instance-segmentation-using-mask-r-cnn-in-opencv-python-c/",
  },
  {
    id: 66,
    type: "article",
    title: "Facial Landmark Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "DLib", "Numpy"],
    datePublished: "April 3, 2017",
    projectURL: "https://www.pyimagesearch.com/2017/04/03/facial-landmarks-dlib-opencv-python/",
  },
  {
    id: 65,
    type: "article",
    title: "Text Skew Correction",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "February 20, 2017",
    projectURL: "https://www.pyimagesearch.com/2017/02/20/text-skew-correction-opencv-python/",
  },
  {
    id: 64,
    type: "article",
    title: "OCR and Text Recognition",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Tesseract", "Numpy"],
    datePublished: "September 17, 2018",
    projectURL:
      "https://www.pyimagesearch.com/2018/09/17/opencv-ocr-and-text-recognition-with-tesseract/",
  },
  {
    id: 63,
    type: "article",
    title: "People Counter",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "August 13, 2018",
    projectURL: "https://www.pyimagesearch.com/2018/08/13/opencv-people-counter/",
  },
  {
    id: 62,
    type: "article",
    title: "Text Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "August 20, 2018",
    projectURL:
      "https://www.pyimagesearch.com/2018/08/20/opencv-text-detection-east-text-detector/",
  },
  {
    id: 61,
    type: "article",
    title: "Semantic Segmentation",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "September 3, 2018",
    projectURL:
      "https://www.pyimagesearch.com/2018/09/03/semantic-segmentation-with-opencv-and-deep-learning/",
  },

  {
    id: 60,
    type: "article",
    title: "Object Tracking",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy", "CamShift"],
    datePublished: "July 2018",
    projectURL:
      "https://www.pyimagesearch.com/wp-content/uploads/2014/11/opencv_crash_course_camshift.pdf",
  },
  {
    id: 59,
    type: "article",
    title: "Face Clustering",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "July 9, 2018",
    projectURL: "https://www.pyimagesearch.com/2018/07/09/face-clustering-with-python/",
  },
  {
    id: 58,
    type: "article",
    title: "Barcode Scanner",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "ZBar", "Numpy"],
    datePublished: "May 21, 2018",
    projectURL:
      "https://www.pyimagesearch.com/2018/05/21/an-opencv-barcode-and-qr-code-scanner-with-zbar/",
  },
  {
    id: 57,
    type: "article",
    title: "Saliency Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "July 16, 2018",
    projectURL: "https://www.pyimagesearch.com/2018/07/16/opencv-saliency-detection/",
  },
  {
    id: 56,
    type: "article",
    title: "Face Detection",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy"],
    datePublished: "February 26, 2018",
    projectURL:
      "https://www.pyimagesearch.com/2018/02/26/face-detection-with-opencv-and-deep-learning/",
  },
  {
    id: 55,
    type: "article",
    title: "Document Scanner",
    category: ["ml-ai"],
    tech: ["Python", "OpenCV", "Numpy", "SciKit"],
    datePublished: "September 1, 2014",
    projectURL:
      "https://www.pyimagesearch.com/2014/09/01/build-kick-ass-mobile-document-scanner-just-5-minutes/",
  },
  {
    id: 54,
    type: "article",
    title: "Music Recommender",
    category: ["ml-ai"],
    tech: ["Python", "SciKit", "Numpy", "Pandas"],
    datePublished: "Apr 24, 2017",
    projectURL: "https://towardsdatascience.com/how-to-build-a-simple-song-recommender-296fcbc8c85",
  },
  {
    id: 53,
    type: "article",
    title: "Predict Quality of Wine",
    category: ["ml-ai"],
    tech: ["Python", "Matplotlib", "Numpy", "Pandas"],
    datePublished: "7 FEBRUARY 2018",
    souce: "freeCodeCamp",
    projectURL:
      "https://www.freecodecamp.org/news/using-data-science-to-understand-what-makes-wine-taste-good-669b496c67ee/",
  },
  {
    id: 52,
    type: "video",
    title: "Genetic Algorithms",
    category: ["ml-ai"],
    tech: ["Python", "SciKit", "Numpy", "Pandas"],
    datePublished: "Nov 11, 2016",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=dSofAXnnFrY",
  },
  {
    id: 51,
    type: "video",
    title: "DeepDream",
    category: ["ml-ai"],
    tech: ["Python", "TensorFlow", "Visualization"],
    datePublished: "Nov 5, 2016",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=MrBzgvUNr4w",
  },
  {
    id: 50,
    type: "video",
    title: "Stock Price Prediction",
    category: ["ml-ai"],
    tech: ["Python", "SciKit", "Matplotlib"],
    datePublished: "Oct 29, 2016",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=SSu00IRRraY",
  },
  {
    id: 49,
    type: "video",
    title: "Movie Recommendation Systems",
    category: ["ml-ai"],
    tech: ["Python", "LightFM"],
    datePublished: "Oct 21, 2016",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=9gBC9R-msAk",
  },
  {
    id: 48,
    type: "video",
    title: "Twitter Sentiment Analysis",
    category: ["ml-ai"],
    tech: ["Python", "API"],
    datePublished: "Oct 14, 2016",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=o_OZdbCzHUA",
  },
  {
    id: 47,
    type: "article",
    title: "Arcade Shooter",
    category: ["game-dev"],
    tech: ["LUA", "LÖVE"],
    datePublished: "Feb 14, 2018",
    projectURL: "https://github.com/adnzzzzZ/blog/issues/30",
  },
  {
    id: 46,
    type: "article",
    title: "Reddit Client",
    category: ["mob-dev"],
    tech: ["Android", "Kotlin"],
    datePublished: "Jan 27, 2016",
    projectURL:
      "https://android.jlelse.eu/learn-kotlin-while-developing-an-android-app-introduction-567e21ff9664",
  },
  {
    id: 45,
    type: "video",
    title: "Todo App",
    category: ["web-dev"],
    tech: ["Vue", "JavaScript", "CSS3", "HTML5"],
    datePublished: "Feb 13, 2018",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=78tNYZUS-ps",
  },
  {
    id: 44,
    type: "article",
    title: "Blog App",
    category: ["web-dev"],
    tech: ["Vue", "GraphQL", "Apollo", "JavaScript", "CSS3", "HTML5"],
    datePublished: "February 22, 2018",
    projectURL: "https://scotch.io/tutorials/build-a-blog-with-vue-graphql-and-apollo-client",
  },
  {
    id: 43,
    type: "article",
    title: "Simple Budgeting App",
    category: ["web-dev"],
    tech: ["Vue", "Bulma", "JavaScript", "CSS3", "HTML5"],
    datePublished: "Mar 21, 2017",
    projectURL: "https://matthiashager.com/complete-vuejs-application-tutorial",
  },
  {
    id: 42,
    type: "article",
    title: "Search Bot",
    category: ["web-dev"],
    tech: ["Node", "Twilio", "Cheerio", "API", "Automation", "JavaScript"],
    datePublished: "3 JUNE 2018",
    projectURL:
      "https://www.freecodecamp.org/news/how-to-build-a-simple-search-bot-in-30-minutes-eb56fcedcdb1/",
  },
  {
    id: 41,
    type: "article",
    title: "Twitter Bot",
    category: ["web-dev"],
    tech: ["Node", "JavaScript", "API", "Automation"],
    datePublished: "May 30, 2017",
    projectURL:
      "https://codeburst.io/build-a-simple-twitter-bot-with-node-js-in-just-38-lines-of-code-ed92db9eb078",
  },
  {
    id: 40,
    type: "article",
    title: "Real-Time Markdown Editor",
    category: ["web-dev"],
    tech: ["Node", "JavaScript", "Express", "Redis", "HTML5", "CSS3"],
    datePublished: "July 01, 2015",
    projectURL: "https://scotch.io/tutorials/building-a-real-time-markdown-viewer",
  },
  {
    id: 39,
    type: "article",
    title: "Todo App",
    category: ["web-dev"],
    tech: ["Angular", "TypeScript", "RxJS", "HTML5", "CSS3"],
    datePublished: "2/2/2018",
    projectURL: "http://www.discoversdk.com/blog/intro-to-angular-and-the-evolution-of-the-web",
  },
  {
    id: 38,
    type: "article",
    title: "Hacker News Client",
    category: ["web-dev"],
    tech: ["Angular", "RxJS", "Webpack", "HTML5", "CSS3", "JavaScript"],
    datePublished: "September 16, 2016",
    projectURL: "https://houssein.me/angular2-hacker-news",
  },
  {
    id: 37,
    type: "video",
    title: "Random Quote Machine",
    category: ["web-dev"],
    tech: ["React", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-10-02",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=3QngsWA9IEE",
  },
  {
    id: 36,
    type: "video",
    title: "Todoist Clone",
    category: ["web-dev"],
    tech: ["React", "Firebase", "JavaScript", "Testing", "HTML5", "CSS3"],
    datePublished: "2019-08-27",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=hT3j87FMR6M",
  },
  {
    id: 35,
    type: "article",
    title: "Chat App with Sentiment Analysis",
    category: ["web-dev", "ml-ai"],
    tech: ["NextJS", "Pusher", "Sentiment", "Node", "React", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-06-08",
    source: "Hackernoon",
    projectURL:
      "https://hackernoon.com/build-an-appointment-scheduler-using-react-twilio-and-cosmic-js-95377f6d1040",
  },
  {
    id: 34,
    type: "article",
    title: "Appointment Scheduler",
    category: ["web-dev"],
    tech: ["React", "Twilio", "CosmicJS", "Material-UI", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2020-03-13",
    source: "Hackernoon",
    projectURL:
      "https://hackernoon.com/build-an-appointment-scheduler-using-react-twilio-and-cosmic-js-95377f6d1040",
  },
  {
    id: 33,
    type: "article",
    title: "Game of Life",
    category: ["web-dev", "game-dev"],
    tech: ["React", "2D", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-05-03",
    source: "freeCodeCamp",
    projectURL:
      "https://www.freecodecamp.org/news/create-gameoflife-with-react-in-one-hour-8e686a410174",
  },
  {
    id: 32,
    type: "article",
    title: "News App",
    category: ["web-dev"],
    tech: ["React Native", "Node", "API", "React", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-04-21",
    source: "freeCodeCamp",
    projectURL:
      "https://www.freecodecamp.org/news/create-a-news-app-using-react-native-ced249263627",
  },
  {
    id: 31,
    type: "article",
    title: "Chat App",
    category: ["web-dev"],
    tech: ["React", "Redux", "Redux Saga", "Web Sockets", "Node", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2017-12-07",
    source: "freeCodeCamp",
    projectURL:
      "https://www.freecodecamp.org/news/how-to-build-a-chat-application-using-react-redux-redux-saga-and-web-sockets-47423e4bc21a/",
  },
  {
    id: 30,
    type: "article",
    title: "Todo App",
    category: ["web-dev"],
    tech: [
      "React Native",
      "GraphQL",
      "Apollo",
      "API",
      "Hasura",
      "React",
      "JavaScript",
      "HTML5",
      "CSS3",
    ],
    datePublished: "2018-04-13",
    projectURL:
      "https://hasura.io/blog/tutorial-fullstack-react-native-with-graphql-and-authentication-18183d13373a",
  },
  {
    id: 29,
    type: "article",
    title: "Chrome Extension",
    category: ["web-dev"],
    tech: ["React", "Parcel", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-03-25",
    projectURL:
      "https://www.freecodecamp.org/news/building-chrome-extensions-in-react-parcel-79d0240dd58f/",
  },
  {
    id: 28,
    type: "article",
    title: "Real-Time Twitter Stream",
    category: ["web-dev"],
    tech: [
      "React",
      "Node",
      "API",
      "Express",
      "Handlebars",
      "Browserify",
      "Mongoose",
      "MongoDB",
      "Socket.io",
      "nTwitter",
      "JavaScript",
      "HTML5",
      "CSS3",
    ],
    datePublished: "2014-10-21",
    projectURL:
      "https://scotch.io/tutorials/build-a-real-time-twitter-stream-with-node-and-react-js",
  },
  {
    id: 27,
    type: "article",
    title: "Movie Voting App",
    category: ["web-dev"],
    tech: ["React", "Redux", "API", "Immutable", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2016-02-24",
    projectURL: "https://teropa.info/blog/2015/09/10/full-stack-redux-tutorial.html",
  },
  {
    id: 26,
    type: "article",
    title: "Yelp Clone",
    category: ["web-dev"],
    tech: ["React", "Google Maps", "API", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2016-05-19",
    projectURL: "https://www.newline.co/fullstack-react/articles/react-tutorial-cloning-yelp",
  },
  {
    id: 25,
    type: "article",
    title: "Trello Clone",
    category: ["web-dev"],
    tech: ["React", "Elixir", "Phoenix", "JWT", "JavaScript", "HTML5", "CSS3"],
    datePublished: "2016-01-04",
    projectURL:
      "http://codeloveandboards.com/blog/2016/01/04/trello-tribute-with-phoenix-and-react-pt-1",
  },
  {
    id: 24,
    type: "article",
    title: "Todo App",
    category: ["mob-dev"],
    tech: ["React Native", "Android", "iOS", "JavaScript"],
    datePublished: "2016-11-15",
    projectURL: "https://egghead.io/courses/build-a-react-native-todo-application",
  },
  {
    id: 23,
    type: "video",
    title: "Handmade Hero",
    category: ["game-dev"],
    tech: ["C/C++", "OpenGL", "2D"],
    datePublished: "2014-11-17",
    projectURL: "https://handmadehero.org/watch",
  },
  {
    id: 22,
    type: "article",
    title: "Breakout",
    category: ["game-dev"],
    tech: ["C/C++", "OpenGL", "2D"],
    datePublished: "2008-12-14",
    projectURL: "https://learnopengl.com/In-Practice/2D-Game/Breakout",
  },
  {
    id: 21,
    type: "article",
    title: "Tetris",
    category: ["game-dev"],
    tech: ["C/C++", "2D"],
    datePublished: "2008-12-14",
    projectURL:
      "http://javilop.com/gamedev/tetris-tutorial-in-c-platform-independent-focused-in-game-logic-for-beginners/",
  },
  {
    id: 20,
    type: "article",
    title: "NES game",
    category: ["game-dev"],
    tech: ["C/C++", "Python", "2D"],
    datePublished: "2018-09-05",
    projectURL: "https://nesdoug.com/",
  },
  {
    id: 19,
    type: "article",
    title: "Photo Library Viewer",
    category: ["mob-dev"],
    tech: ["C#", "iOS", "Xamarin", "Visual Studio", "Android", ".NET"],
    datePublished: "2016-07-21",
    projectURL:
      "https://www.raywenderlich.com/1044-building-ios-apps-with-xamarin-and-visual-studio",
  },
  {
    id: 18,
    type: "video",
    title: "Wiki-Style CMS",
    category: ["web-dev"],
    tech: ["C#", ".NET", "Razor Pages"],
    datePublished: "2018-11-11",
    projectURL: "https://www.youtube.com/playlist?list=PLVMqA0_8O85yC78I4Xj7z48ES48IQBa7p",
  },
  {
    id: 17,
    type: "article",
    title: "Roguelike Game",
    category: ["game-dev"],
    tech: ["C#", ".NET", "RogueSharp", "MonoGame", "RLNet", "SadConsole", "2D"],
    datePublished: "2015-01-09",
    projectURL: "https://roguesharp.wordpress.com/",
  },
  {
    id: 16,
    type: "article",
    title: "Simple RPG Game",
    category: ["game-dev"],
    tech: ["C#", "SQL", "2D"],
    datePublished: "2014-05-17",
    projectURL: "http://scottlilly.com/learn-c-by-building-a-simple-rpg-index",
  },
  {
    id: 15,
    type: "video",
    title: "Spotify Inspired Web Design",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3"],
    source: "YouTube",
    datePublished: "2019-03-09",
    projectURL: "https://www.youtube.com/watch?v=uKgn-To1C4Q",
  },
  {
    id: 14,
    type: "video",
    title: "Microsoft Homepage Clone",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3", "JavaScript"],
    source: "YouTube",
    datePublished: "2020-02-11",
    projectURL: "https://www.youtube.com/watch?v=uKgn-To1C4Q",
  },
  {
    id: 13,
    type: "article",
    title: "Simple Gantt Chart",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3", "JavaScript"],
    datePublished: "2019-09-26",
    projectURL:
      "https://webdesign.tutsplus.com/tutorials/build-a-simple-gantt-chart-with-css-and-javascript--cms-33813",
  },
  {
    id: 12,
    type: "article",
    title: "Job Scraping App",
    category: ["web-dev"],
    tech: ["Node", "JavaScript", "REST", "API", "Express", "Handlebars", "Material Design Lite"],
    source: "freeCodeCamp",
    datePublished: "2018-07-11",
    projectURL:
      "https://www.freecodecamp.org/news/how-i-built-a-job-scraping-web-app-using-node-js-and-indreed-7fbba124bbdc/",
  },
  {
    id: 11,
    type: "video",
    title: "E-Commerce App",
    category: ["web-dev"],
    tech: ["React", "Bootstrap", "JavaScript", "HTML5", "CSS3", "JQuery", "Context API"],
    source: "YouTube",
    datePublished: "2018-12-22",
    projectURL: "https://www.youtube.com/watch?v=wPQ1-33teR4",
  },
  {
    id: 10,
    type: "video",
    title: "Netflix Landing Page",
    category: ["web-dev"],
    tech: ["HTML5", "CSS3", "JavaScript"],
    source: "YouTube",
    datePublished: "2019-05-21",
    projectURL: "https://www.youtube.com/watch?v=P7t13SGytRk",
  },
  {
    id: 9,
    type: "article",
    title: "AI Chatbot",
    category: ["web-dev"],
    tech: [
      "Web Speech API",
      "Node",
      "JavaScript",
      "Express",
      "Socket.io",
      "Artificial Intelligence",
    ],
    datePublished: "2017-08-07",
    projectURL: "https://www.smashingmagazine.com/2017/08/ai-chatbot-web-speech-api-node-js",
  },
  {
    id: 8,
    type: "video",
    title: "Social Networking App",
    category: ["web-dev"],
    tech: [
      "React",
      "Node",
      "Redux",
      "Firebase",
      "REST",
      "API",
      "HTML5",
      "CSS3",
      "JavaScript",
      "Express",
      "Material-UI",
    ],
    source: "YouTube",
    datePublished: "2019-06-24",
    projectURL: "https://www.youtube.com/watch?v=m_u6P5k0vP0",
  },
  {
    id: 7,
    type: "article",
    title: "Blockchain",
    category: ["web-dev"],
    tech: ["Node", "JavaScript", "Cryptography", "Blockchain"],
    datePublished: "2019-09-15",
    projectURL: "https://www.hackdoor.io/articles/BwJeDQnm/writing-a-blockchain-in-node-js",
  },
  {
    id: 6,
    type: "article",
    title: "BitTorrent Client",
    category: ["web-dev"],
    tech: ["Node", "JavaScript", "TCP", "Computer Networks"],
    datePublished: "2016-05-04",
    projectURL:
      "https://allenkim67.github.io/programming/2016/05/04/how-to-make-your-own-bittorrent-client.html",
  },
  {
    id: 5,
    type: "article",
    title: "URL Shortener with JavaScript",
    category: ["web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "2018-10-11",
    source: "freeCodeCamp",
    projectURL:
      "https://www.freecodecamp.org/news/building-a-simple-url-shortener-with-just-html-and-javascript-6ea1ecda308c/",
  },
  {
    id: 4,
    type: "article",
    title: "Todo List App with JavaScript",
    category: ["web-dev"],
    tech: ["JavaScript", "HTML5", "CSS3"],
    datePublished: "2019-10-23",
    projectURL: "https://freshman.tech/todo-list",
  },
  {
    id: 3,
    type: "article",
    title: "JavaScript Animations with Anime.js",
    category: ["web-dev"],
    tech: ["JavaScript", "CSS3", "Library", "HTML5", "API"],
    datePublished: "2018-08-23",
    source: "Medium",
    projectURL:
      "https://medium.com/@ajmeyghani/creating-javascript-animations-with-anime-js-f2b14716cdc6",
  },
  {
    id: 2,
    type: "article",
    title: "WhatsApp Clone with React Native",
    category: ["mob-dev"],
    tech: [
      "React Native",
      "Node",
      "GraphQL",
      "Apollo",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Express",
      "API",
      "SQLite",
      "Android",
      "iOS",
    ],
    datePublished: "2017-04-9",
    source: "Medium",
    projectURL:
      "https://medium.com/react-native-training/building-chatty-a-whatsapp-clone-with-react-native-and-apollo-part-1-setup-68a02f7e11",
  },
  {
    id: 1,
    type: "video",
    title: "Job Board App with React",
    category: ["web-dev"],
    tech: [
      "React",
      "Node",
      "Cron",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Express",
      "REST",
      "API",
      "Redis",
    ],
    datePublished: "11-26-2019",
    source: "YouTube",
    projectURL: "https://www.youtube.com/watch?v=lauywdXKEXI",
  },
];
